// src/styles/styles.js
// ─────────────────────────────────────────────────────────────
// Todos los estilos de la app centralizados aquí.
// Para cambiar colores, tipografías o espaciados, edita este archivo.
// ─────────────────────────────────────────────────────────────

export const styles = {
  // ── ROOT / LAYOUT ─────────────────────────────────────────
  root: {
    minHeight: "100vh",
    background: "#0D0D1A",
    color: "#E8E8F0",
    fontFamily: "'Segoe UI', system-ui, sans-serif",
    maxWidth: 480,
    margin: "0 auto",
    paddingBottom: 40,
  },

  // ── HEADER ────────────────────────────────────────────────
  header: {
    background: "linear-gradient(135deg, #12122A 0%, #1A1A3E 100%)",
    borderBottom: "1px solid #2A2A4A",
    padding: "20px 20px 0",
  },
  headerInner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  headerTag: {
    fontSize: 10,
    letterSpacing: 2,
    color: "#7070A0",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  headerTitle: {
    margin: 0,
    fontSize: 28,
    fontWeight: 800,
    color: "#fff",
    letterSpacing: -0.5,
  },
  headerSub: {
    margin: "4px 0 0",
    fontSize: 12,
    color: "#7070A0",
  },
  netoBox: {
    background: "#1E1E40",
    border: "1px solid #3A3A6A",
    borderRadius: 12,
    padding: "10px 14px",
    textAlign: "right",
  },
  netoLabel: {
    display: "block",
    fontSize: 10,
    color: "#7070A0",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  netoVal: {
    display: "block",
    fontSize: 18,
    fontWeight: 800,
    marginTop: 2,
  },

  // ── VISTA TABS (Hoy / Semana / Mes) ───────────────────────
  vistaTabs: {
    display: "flex",
    gap: 4,
    paddingBottom: 0,
  },
  vistaBtn: {
    flex: 1,
    padding: "10px 0",
    border: "none",
    background: "transparent",
    color: "#6060A0",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    borderBottom: "3px solid transparent",
    transition: "all 0.2s",
  },
  vistaBtnActive: {
    color: "#fff",
    borderBottom: "3px solid #7B68EE",
  },

  // ── STATS CARDS ───────────────────────────────────────────
  statsRow: {
    display: "flex",
    gap: 10,
    padding: "16px 16px 0",
  },
  statCard: {
    flex: 1,
    background: "#14142A",
    border: "1px solid",
    borderRadius: 12,
    padding: "12px 10px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
  },
  statEmoji: { fontSize: 18 },
  statLabel: {
    fontSize: 10,
    color: "#6060A0",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  statVal: { fontSize: 14, fontWeight: 800 },

  // ── MAIN TABS ─────────────────────────────────────────────
  mainTabs: {
    display: "flex",
    gap: 8,
    padding: "16px 16px 0",
  },
  mainTab: {
    flex: 1,
    padding: "10px 4px",
    border: "1px solid #2A2A4A",
    borderRadius: 10,
    background: "#14142A",
    color: "#6060A0",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  mainTabActive: {
    background: "#7B68EE",
    borderColor: "#7B68EE",
    color: "#fff",
  },

  // ── CONTENT AREA ──────────────────────────────────────────
  content: { padding: "16px" },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: "#6060A0",
    marginTop: 16,
    marginBottom: 10,
  },
  empty: {
    color: "#4040A0",
    textAlign: "center",
    padding: "30px 0",
    fontSize: 14,
  },

  // ── RESUMEN: CATEGORIA CARDS ───────────────────────────────
  catGrid: { display: "flex", flexDirection: "column", gap: 8 },
  catCard: {
    background: "#14142A",
    borderRadius: 10,
    padding: "12px 14px",
    display: "flex",
    alignItems: "center",
    gap: 12,
    borderLeft: "4px solid",
  },
  catEmoji: { fontSize: 22 },
  catName: { fontSize: 13, fontWeight: 600, color: "#C0C0E0" },
  catTotal: { fontSize: 16, fontWeight: 800, marginTop: 2 },
  catBadge: {
    marginLeft: "auto",
    fontSize: 10,
    fontWeight: 700,
    padding: "3px 8px",
    borderRadius: 20,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // ── RESUMEN: BAR CHART ────────────────────────────────────
  barChart: { display: "flex", flexDirection: "column", gap: 8 },
  barRow: { display: "flex", alignItems: "center", gap: 8 },
  barLabel: { fontSize: 11, color: "#8080B0", minWidth: 110, flexShrink: 0 },
  barTrack: {
    flex: 1,
    background: "#1E1E3A",
    borderRadius: 6,
    height: 10,
    overflow: "hidden",
  },
  barFill: { height: "100%", borderRadius: 6, transition: "width 0.4s ease" },
  barAmt: {
    fontSize: 11,
    color: "#A0A0C0",
    minWidth: 76,
    textAlign: "right",
    flexShrink: 0,
  },

  // ── FORMULARIO ────────────────────────────────────────────
  formBox: { display: "flex", flexDirection: "column", gap: 0 },
  editBanner: {
    background: "#2A2A10",
    border: "1px solid #6060FF",
    borderRadius: 10,
    padding: "10px 14px",
    fontSize: 13,
    color: "#A0A0FF",
    marginBottom: 8,
  },
  cancelLink: {
    background: "none",
    border: "none",
    color: "#FF6B6B",
    cursor: "pointer",
    fontSize: 13,
    padding: 0,
    textDecoration: "underline",
  },
  catGroupLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: "#6060A0",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  catSelect: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  catBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 12px",
    borderRadius: 10,
    border: "2px solid",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 600,
    transition: "all 0.15s",
  },
  catBtnLabel: { color: "#C0C0E0" },
  input: {
    width: "100%",
    background: "#14142A",
    border: "1px solid #2A2A4A",
    borderRadius: 10,
    padding: "12px 14px",
    color: "#E8E8F0",
    fontSize: 15,
    outline: "none",
    boxSizing: "border-box",
    marginBottom: 4,
  },
  submitBtn: {
    marginTop: 16,
    width: "100%",
    padding: "14px",
    background: "linear-gradient(135deg, #7B68EE, #9B85FF)",
    border: "none",
    borderRadius: 12,
    color: "#fff",
    fontSize: 15,
    fontWeight: 800,
    cursor: "pointer",
    letterSpacing: 0.3,
  },

  // ── HISTORIAL: REGISTRO ITEM ───────────────────────────────
  registro: {
    background: "#14142A",
    borderRadius: 12,
    padding: "12px 14px",
    marginBottom: 8,
    display: "flex",
    alignItems: "center",
    gap: 10,
    position: "relative",
    overflow: "hidden",
  },
  regAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    borderRadius: "12px 0 0 12px",
  },
  regEmoji: { fontSize: 22, flexShrink: 0 },
  regInfo: { flex: 1, minWidth: 0 },
  regCat: { fontSize: 13, fontWeight: 700, color: "#C0C0E0" },
  regNota: {
    fontSize: 11,
    color: "#6060A0",
    marginTop: 2,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  regFecha: { fontSize: 10, color: "#5050A0", marginTop: 4 },
  regRight: { textAlign: "right", flexShrink: 0 },
  regMonto: { fontSize: 15, fontWeight: 800 },
  regActions: {
    display: "flex",
    gap: 4,
    justifyContent: "flex-end",
    marginTop: 4,
  },
  editBtn: {
    background: "#1E1E3A",
    border: "1px solid #3A3A6A",
    borderRadius: 6,
    padding: "4px 8px",
    cursor: "pointer",
    fontSize: 13,
  },
  deleteBtn: {
    background: "#2A1010",
    border: "1px solid #5A2020",
    borderRadius: 6,
    padding: "4px 8px",
    cursor: "pointer",
    fontSize: 13,
  },

  // ── MODAL DE CONFIRMACIÓN ─────────────────────────────────
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  modal: {
    background: "#1A1A30",
    border: "1px solid #3A3A6A",
    borderRadius: 16,
    padding: "28px 24px",
    textAlign: "center",
    width: 280,
  },
  modalEmoji: { fontSize: 36, marginBottom: 10 },
  modalTitle: { fontSize: 17, fontWeight: 800, color: "#E8E8F0", marginBottom: 6 },
  modalSub: { fontSize: 13, color: "#6060A0", marginBottom: 20 },
  modalBtns: { display: "flex", gap: 10 },
  modalCancel: {
    flex: 1,
    padding: "10px",
    background: "#14142A",
    border: "1px solid #3A3A6A",
    borderRadius: 10,
    color: "#A0A0C0",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  modalConfirm: {
    flex: 1,
    padding: "10px",
    background: "#FF3D00",
    border: "none",
    borderRadius: 10,
    color: "#fff",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
  },

  // ── TOAST (NOTIFICACIÓN) ──────────────────────────────────
  toast: {
    position: "fixed",
    bottom: 24,
    left: "50%",
    transform: "translateX(-50%)",
    padding: "10px 22px",
    borderRadius: 30,
    color: "#fff",
    fontWeight: 700,
    fontSize: 13,
    zIndex: 200,
    boxShadow: "0 4px 20px rgba(0,0,0,0.4)",
    whiteSpace: "nowrap",
  },
};
